import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Award, Target, Users } from "lucide-react";
import { Card } from "@/components/ui/card";
export function AboutSection() {
    const stats = [
        { icon: Award, label: "Years of Excellence", value: "30+", color: "text-primary" },
        { icon: Target, label: "Projects Delivered", value: "500+", color: "text-primary" },
        { icon: Users, label: "Happy Clients", value: "5K+", color: "text-primary" },
    ];
    return (_jsx("section", { id: "about", className: "py-20 bg-muted/30", children: _jsxs("div", { className: "max-w-7xl mx-auto px-4 sm:px-6 lg:px-8", children: [_jsxs("div", { className: "text-center mb-12", children: [_jsxs("h2", { className: "font-heading font-bold text-3xl sm:text-4xl md:text-5xl mb-4", children: ["About ", _jsx("span", { className: "text-primary", children: "Orange Sign" })] }), _jsx("p", { className: "text-lg text-muted-foreground max-w-3xl mx-auto leading-relaxed", children: "A premium printing and signage studio delivering excellence since 1998" })] }), _jsx("div", { className: "grid md:grid-cols-3 gap-6 mb-12", children: stats.map((stat) => (_jsxs(Card, { className: "p-6 text-center hover-elevate", children: [_jsx("div", { className: "flex justify-center mb-4", children: _jsx("div", { className: "w-16 h-16 rounded-full bg-primary/10 flex items-center justify-center", children: _jsx(stat.icon, { className: `h-8 w-8 ${stat.color}` }) }) }), _jsx("div", { className: "font-heading font-bold text-4xl mb-2", children: stat.value }), _jsx("div", { className: "text-sm text-muted-foreground", children: stat.label })] }, stat.label))) }), _jsx("div", { className: "max-w-4xl mx-auto", children: _jsxs(Card, { className: "p-8", children: [_jsx("h3", { className: "font-heading font-semibold text-2xl mb-4", children: "Our Story" }), _jsx("p", { className: "text-muted-foreground leading-relaxed mb-4", children: "Orange Sign has been at the forefront of the printing and signage industry for over three decades. We specialize in premium panaflex printing, LED signage, and large-format advertising solutions that help businesses stand out and make lasting impressions." }), _jsx("p", { className: "text-muted-foreground leading-relaxed mb-4", children: "Our commitment to quality and innovation has made us the trusted partner for thousands of businesses across Islamabad and Rawalpindi. From small startups to large enterprises, we deliver visual solutions that transform brands into unforgettable experiences." }), _jsxs("div", { className: "grid sm:grid-cols-2 gap-4 mt-6", children: [_jsxs("div", { children: [_jsx("h4", { className: "font-heading font-semibold mb-2", children: "Coverage" }), _jsx("p", { className: "text-sm text-muted-foreground", children: "Nationwide printing solutions across Islamabad and Rawalpindi" })] }), _jsxs("div", { children: [_jsx("h4", { className: "font-heading font-semibold mb-2", children: "Working Hours" }), _jsx("p", { className: "text-sm text-muted-foreground", children: "Mon\u2013Sat, 9AM\u20138PM" })] })] })] }) })] }) }));
}
//# sourceMappingURL=AboutSection.js.map